VideoManager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include('upload.urls')),
    path('video/', include('video.urls')),
    path('', include('home.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from home import views
from django.urls import path


app_name="home"

urlpatterns = [
    path('list', views.videos_list, name="list"),
    path('search/<str:search_val>', views.search, name="search"),
    path("fix", views.fix),
    path('', views.index,name="home"),

]

upload/urls.py
from django.urls import path
from upload import views

app_name='upload'

urlpatterns = [
    path('', views.index, name='index')
]

video/urls.py
from django.urls import path
from video import views

app_name = 'video'

urlpatterns= [
    path('online/<str:uuid>', views.online, name="online"),
    path('delete/<str:uuid>', views.delete, name="delete"),
]

home/models.py
from django.db import models

# Create your models here.

upload/models.py
from django.db import models

# Create your models here.

video/models.py
from datetime import datetime
import os
import time
from django.db import models
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext as _

# Create your models here.

def get_movie_path(self, filename):
    ext = filename.split('.')
    ext = ext[-1]
    # fileStat = os.stat(self.video.path)
    # rendered_time = datetime.fromtimestamp(fileStat.st_mtime)
    title = filename
    title = title.lower().replace(' ', '_')
    return f'videos/{self.uuid}/{title}'

def get_gif_path(self, filename):
    ext = filename.split('.')
    ext = ext[-1]
    fileStat = os.stat(self.video.path)
    rendered_time = datetime.fromtimestamp(fileStat.st_mtime)
    title = f'{rendered_time.year}-{rendered_time.month}-{rendered_time.day}{rendered_time.hour}{rendered_time.minute}'
    title = title.lower().replace(' ', '_')
    title = title+'_gif'
    return f'videos/{self.uuid}/{title}.gif'

def generate_id_length():
    return get_random_string(10)

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name
    
class Actor(models.Model):
    CHOICES_SEX = (('male','male'),('female', 'female'))
    name = models.CharField(max_length=300)
    sex = models.CharField(max_length=300, choices=CHOICES_SEX)
    def __str__(self) -> str:
        return self.name

class Video(models.Model):
    title = models.CharField(max_length=300, blank=True, null=True)
    uuid = models.CharField(default=generate_id_length,max_length=10,unique=True)
    video = models.FileField(
        verbose_name=_("فایل ویدیو"),
        upload_to=get_movie_path,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'mp3','ts'])
        ])
    date = models.CharField(max_length=300, null=True,blank=True)
    cast = models.ManyToManyField(Actor, blank=True)
    gif = models.FileField(
        verbose_name=_("فایل گیف"),
        upload_to=get_gif_path,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['gif', 'png'])
        ],null=True, blank=True)
    
    published_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True)
    def __str__(self) -> str:
        if self.title:
            return self.title
        elif self.date:
            return self.date
        else:
            return self.video.name.split('/')[-1]    
    class Meta:
        ordering = ['-published_at']


        



@receiver(models.signals.post_delete, sender=Video)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    main_folder = "media/"+get_movie_path(instance,"")
    if instance.video:
        video_path = instance.video.path
        if os.path.isfile(video_path):
            os.remove(video_path)
    if instance.gif:
        gif_path = instance.gif.path
        if os.path.isfile(gif_path):
            os.remove(gif_path)
    try:
        os.rmdir(main_folder)
    except Exception as e:
        pass 
    

home/views.py
import math
from django.http import HttpResponse
import json
from django.shortcuts import render
from video.models import Video,Tag
from video.serializer import serializer
import json
from django.http import HttpResponse
from django.shortcuts import redirect
# Create your views here.

def videos_list(request):
    errors = []
    page = request.GET.get('page', 1)
    page = int(page)
    first = (page-1)*21
    last = page*21
    videos = Video.objects.all()[first:last]
    serialized = [serializer(video) for video in videos]

    return HttpResponse(json.dumps(serialized), content_type="application/json")
    
def get_tags(searched_val):
    results =[]
    for tag in Tag.objects.all():
        splitted = ''.join(tag.name.lower().split(' '))
        if splitted.find(searched_val) != -1:
            videos = Video.objects.filter(tags__name__in=[tag.name])
            results.extend([serializer(video) for video in videos])
    return results

def index(request):
    page = request.GET.get('page',1)
    page=int(page)
    last_page = math.ceil(len(Video.objects.all()) / 21)
    first_page = 1
    context = {
        'has_next': page < last_page,
        'hast_prev': page > 1,
        'next': page + 1 if page < last_page else None,
        'prev': page -1 if page > 1 else None,
        'page_obj': range(1,last_page+1), 
        'page': page
    }
    return render(request,'home.html',context=context)

def search(request, search_val):
    if search_val is not None:
        results = []
        for video in Video.objects.all():
            splitted = ''.join(video.title.lower().split(' '))
            if splitted.find(search_val) != -1:
                serialized = serializer(video)
                results.append(serialized)
        tags = get_tags(search_val)
        results.extend(tags)
        return HttpResponse(json.dumps(results), content_type="application/json")

def fix(request):
    names_list = []
    for video in Video.objects.all():
        names_list.append(video.title)
    with open("names.txt", "w", encoding="utf-8") as f:
        f.write(json.dumps(names_list))
    return HttpResponse()

upload/views.py
from datetime import datetime
import json
import math
import os
import cv2
from django.http import HttpResponse
from django.shortcuts import render

from video.forms import CreateVideo
from video.models import Actor, Video

# Create your views here.


def get_gif_path(self, filename):
    ext = filename.split('.')
    ext = ext[-1]
    fileStat = os.stat(self.video.path)
    rendered_time = datetime.fromtimestamp(fileStat.st_mtime)
    title = f'{rendered_time.year}-{rendered_time.month}-{rendered_time.day}{rendered_time.hour}{rendered_time.minute}'
    title = title.lower().replace(' ', '_')
    title = title+'_gif'
    return f'videos/{self.uuid}/{title}.gif'

def index(request):
    if request.method == "GET":
        return render(request, 'upload.html', {'actors': Actor.objects.all()})
    else:
        form = CreateVideo(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            video =request.FILES.get('video')
            instance = Video(title=cleaned_data['title'],video=video)
            instance.save()
            gif_name = get_gif(instance)
            instance.cast.set(cleaned_data['cast'])
            date = set_date(instance)
            instance.gif.name = gif_name
            instance.date = date
            instance.save()
            return render(request, 'upload.html', {'actors': Actor.objects.all()})
        else:
            return render(request, 'upload.html', {'actors': Actor.objects.all(), 'errors': form.errors})
        
def get_gif(video):
    v = cv2.VideoCapture(video.video.path)
    frames = v.get(cv2.CAP_PROP_FRAME_COUNT)
    fps = v.get(cv2.CAP_PROP_FPS)
    seconds = round(frames / fps)
    duration = math.ceil(seconds / 60)
    pass_sec = duration/2 * 60
    gif_name = get_gif_path(video, video.video.name.split('/')[-1])
    gif_name2 = os.path.join(os.getcwd(), f'media/{gif_name}')
    gif_name2 = gif_name2.replace('\\', "/")
    command = f'ffmpeg -ss {pass_sec} -t 10 -i "{video.video.path}" -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 "{gif_name2}"'
    print(command)
    os.system(command)
    return gif_name

def set_date(video):
    fileStat = os.stat(video.video.path)
    rendered_time = datetime.fromtimestamp(fileStat.st_mtime)
    return f'{rendered_time.year}-{rendered_time.month}-{rendered_time.day}{rendered_time.hour}-{rendered_time.minute}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Top navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'upload:index' %}">Upload</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" id="search-input" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
    {% block script %}
    {%endblock%}
</body>

</html>

templates/delete_confirm.html
{% extends "base.html" %}

{% block title %}Delete{% endblock title %}

{% block content %}
<div class="jumbotron">
  <h1>Are you sure you want to delete this video?</h1>
  <p>...</p>
  <form action="{% url 'video:delete' uuid %}" method="post">
  {% csrf_token %}
    <div class="row">
      <p class="col-3"><button class="btn btn-danger btn-lg" type="submit">Delete</button></p>
      <p class="col-3"><a class="btn btn-primary btn-lg" href="{% url 'home:home' %}" role="button">Cancel</a></p>
    </div>
	<input type="text" hidden readonly id="page" name="page" value={{page}}>
  </form>
  <script>
  </script>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block title %} Videos {% endblock %}
{% block content %}
<style>
    .videos-holder {
        flex-wrap: wrap;
        column-gap: 20px;
    }

    .card {
        margin-bottom: 20px;
        width: 32%;
    }

    @media (max-width:750px) {
        .card {
            width: 100%;
        }
    }
</style>
<div class="bg-light p-3 rounded d-flex videos-holder">
</div>
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not has_prev %}disabled{% endif %}">
            <a class="page-link" href="?page={{prev}}" tabindex="-1">Previous</a>
        </li>
        {% for i in page_obj %}
        <li class="page-item {% if page == i%}active{% endif %}">
            <a class="page-link" href="?page={{i}}">{{i}} <span class="sr-only"></span></a>
        </li>
        {% endfor %}
        <li class="page-item {% if not has_next %}disabled{% endif %}">
            <a class="page-link" href="?page={{next}}">Next</a>
        </li>
    </ul>
</nav>

{% endblock %}

{% block script %}
<script>
    const holder = document.querySelector('.videos-holder');
    function getVideos() {
        let url = `{% url "home:list" %}${window.location.search}`;
        let all_elements = "";
        let xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.onload = () => {
            let jsoned = JSON.parse(xhr.responseText);
            jsoned.forEach(element => {
                all_elements += `<div class="card">
                    <img src="${element.gif}" class="card-img-top" alt="..." style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title">${element.title}</h5>
                        <p class="card-text"></p>
                        <div class="row">
                            <div class="col-6">
                                <a href="/video/online/${element.uuid}" class="btn btn-primary">Watch Online</a>
                            </div>
                            <div class="col-6">
                                <a href="/video/delete/${element.uuid}?next={{page}}" class="btn btn-danger">Delete</a>
                            </div>

                        </div>
                    </div>
                </div>`;
            });
            holder.innerHTML = all_elements;
        }
        xhr.send();
    }
    function Search(value) {
        let url = `/search/${value}`;
        let all_elements = "";
        let xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.onload = () => {
            let jsoned = JSON.parse(xhr.responseText);
            jsoned.forEach(element => {
                all_elements += `<div class="card">
                    <img src="${element.gif}" class="card-img-top" alt="..." style="height:200px">
                    <div class="card-body">
                        <h5 class="card-title">${element.title}</h5>
                        <p class="card-text"></p>
                        <div class="row">
                            <div class="col-6">
                                <a href="/video/online/${element.uuid}" class="btn btn-primary">Watch Online</a>
                            </div>
                            <div class="col-6">
                                <a href="/video/delete/${element.uuid}" class="btn btn-danger">Delete</a>
                            </div>
    
                        </div>
                    </div>
                </div>`;
            });
            holder.innerHTML = all_elements;
        }
        xhr.send();
    }
    getVideos();
    const searchInput = document.getElementById('search-input');
    let videos = document.querySelectorAll('.card');
    searchInput.onkeyup = () => {
        let value = searchInput.value;
        if (value !== '') {
            Search(value);
        } else {
            getVideos();
        }


    }
</script>
{% endblock %}

templates/online.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online</title>
</head>
<body>
	<style>
		*{
			padding:0;
			margin:0;
			box-sizing:border-box
		}
		video{
		width:100vw;
		height:100vh;
		overflow-x: hidden;
		}
	</style>
    <video src="{{video}}" controls></video>
	<a href="{{video}}">Download</a>
</body>
</html>

templates/upload.html
{% extends 'base.html' %}
{% block title %} Uplaod Video {% endblock %}
{% block content %}
<div class="container">
    <div class="bg-light p-5 rounded">
        <form method="POST" action="{% url 'upload:index' %}" enctype="multipart/form-data">
            {% if errors %}
            <h2>{{ errors }}</h2>
            {% endif %}
            {% csrf_token %}
            <legend>اضافه کردن ویدیو</legend>
            <div class="mb-3 lg-6 sm-12">
                <label for="id_amount" class="form-label">عنوان</label>
                <input type="text" id="id_amount" class="form-control" name="title">
            </div>
            <div class="mb-3 lg-6 sm-12">
                <label for="id_cast" class="form-label">بازیگران</label>
                <select class="form-select" aria-label="Select actor" id="id_cast" name="cast" multiple>
                    {% for actor in actors%}
                    <option value="{{actor.pk}}">{{actor.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3 lg-6 sm-12">
                <label for="formFile" class="form-label">فایل ویدیو</label>
                <input class="form-control" type="file" id="formFile" name="video">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}